[build]
  command = 'npm run ci:build'
  publish = 'build'

[template]
  incoming-hooks = ["Uniform"]

[template.environment]
  UNIFORM_API_KEY='Uniform Optimize API Key'


[build.environment]
  UNIFORM_CLI_BASE_URL='https://uniformapp-dev.s3.amazonaws.com/optimize/'
